
GET http://localhost:8081/api/auth/verify


###

POST http://localhost:8081/api/auth/sign-out


###

POST http://localhost:8081/api/auth/sign-up
Content-Type: application/json

{
    "firstName" : "Cris Vincent",
    "lastName" : "Ferrer",
    "middleName" : "Ga",
    "suffix" : "xs",
    "email" : "test@gmail.com",
    "password" : "123",
    "userType" : 2
}

###

POST http://localhost:8081/api/auth/sign-in
Content-Type: application/json

{
    "email" : "cris@gmail.com",
    "password" : "123"
}


###

POST http://localhost:8081/api/teacher
Content-Type: application/json

{
        "teacherId" : 39,
        "subjectName" : "Programming",
        "description" : "Web Development",
        "subjectCode" : "PROG123",
        "schedule" : "3-5:00 TTH"
}
###
GET http://localhost:8081/api/teacher/class/24

###
POST http://localhost:8081/api/teacher/class/quiz
Content-Type: application/json

{
        "title" : "Test",
        "classid" : 24
}

###
GET http://localhost:8081/api/teacher/class/quiz/15/details

###
POST http://localhost:8081/api/student
Content-Type: application/json

{
        "voucher" :2243794,
        "subjectId" : 85,
        "studentId" : 26

}

###
GET http://localhost:8081/api/student/26
